#!/usr/bin/env node

'use strict';

var c = require("skilstak-colors");
var out = process.stdout; // instead of console.log()

var printPlain = function (message) {
  out.write(c.clear + message + "\n");  
}

var printColor = function (message) {
  while (true) {
    out.write(c.rc() + message + ' ' + c.x);
  }
}

var printMulti = function (message) {
  setInterval(function () { 
    out.write(c.clear + c.multi(message + " "));
    out.write("\n");
  }, 500);
}

var parseArgs = function (message) {
  var who = "world";
  var option = "";
  if (process.argv.length > 3) {
    option = process.argv[2];
    who = process.argv[3];
  } else if (process.argv.length == 3) {
    if (process.argv[2][0] == "-") {
      option = process.argv[2];
    } else {
    who = process.argv[2];
    }
  }
  return {"who":who, "option": option};
}

// main

var p = parseArgs();
var message = "Hello " + p.who + "!";

if (p.option === "-m") {
  printMulti(message)
} else if (p.option === "-c") {
  printColor(message);
} else {
  printPlain(message);
}
