#!/usr/bin/env node

/**
 * @author SkilStak Coding Arts <learn@skilstak.com>
 * @copyright 2015 SkilStak, Inc.
 * @license {link http://unlicense.org/|UNLICENSE}
 *
 * @overview
 *
 * Not yo grandma's hello world command.
 *
 */

'use strict';

var hello = require("hello");
var p = hello.parseArgs();
var message = "Hello " + p.who + "!";

if (p.option === "-m") {
  hello.printMulti(message)
} else if (p.option === "-c") {
  hello.printColor(message);
} else {
  hello.printPlain(message);
}
