#!/usr/bin/env python3

"""Not yo grandma's hello world command.

This is the command line Python program that uses the functions in
the ``hello.py`` module.

This documentation can be displayed with ``pydoc3 ./hello``
or converted to web page with any number of tools.

"""

def print_usage():
    print("""usage:
    hello
    hello You
    hello -f
    hello -f You
    hello -c
    hello -c You
    hello -m
    hello -m You
    hello -h""")

if __name__ == '__main__':
    import hello

    p = hello.parse_args()
    option = p['option']
    message = 'Hello ' + p['name'] + '!'

    # the 'try/except' is to gracefully exit when <cntl>-c
    try:
        if option == "-f":
            hello.print_foreva(message)
        elif option == "-m":
            hello.print_multi(message)
            #print_merica(message)
        elif option == "-c":
            hello.print_color(message)
        elif option == "-h":
            print_usage()
        else:
            hello.print_plain(message)
    except KeyboardInterrupt:
        exit()
