#!/usr/bin/env python3

"""My super cool Python hello world program"""

def print_plain(message):
    """Prints <message> in plain"""
    print(message)


if __name__ == "__main__":
    print_plain("Hello world")
