#!/usr/bin/env python3

import skilstak.colors as c

"""This is my hello world program."""

def print_plain(message):
    print(message)

if __name__ == '__main__':
    from sys import argv

    name = "world"

    if len(argv) == 2:
        name = argv[1] 
    print_plain("Hello " + name + "!")

